steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    id: 'install-deps'
  
  # Step 2: Run Jest tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test:ci']
    env:
      - 'CI=true'
    id: 'run-tests'
    waitFor: ['install-deps']
  
  # Step 3: Build React application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    timeout: '5m'
    id: 'build-app'
    waitFor: ['run-tests']
  
# Step 4: SonarQube analysis
  - name: 'sonarsource/sonar-scanner-cli:latest'
    args:
      - '-Dsonar.host.url=http://35.214.252.38:9000'
      - '-Dsonar.login=$${SONAR_TOKEN}'
      - '-Dsonar.projectKey=apptest'
      - '-Dsonar.sources=src'
      - '-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
    secretEnv: ['SONAR_TOKEN']
    id: 'sonarqube-scan'
    waitFor: ['run-tests']

  
  # Step 5: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA', '.']
    id: 'build-image'
    waitFor: ['build-app']
  
  # Step 6: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA']
    id: 'push-image'
    waitFor: ['build-image']
  
  # Step 7: Trivy vulnerability scan
  - name: 'aquasec/trivy'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Starting vulnerability scan..."
        trivy image --exit-code 1 --severity CRITICAL,HIGH --ignore-unfixed \
        --format json --output /workspace/trivy-results.json \
        ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA
        
        trivy image --exit-code 0 --severity CRITICAL,HIGH --ignore-unfixed \
        ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA
    id: 'trivy-scan'
    waitFor: ['push-image']
  
  # Step 8: Deploy to Cloud Run (only if all checks pass)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
    id: 'deploy'
    waitFor: ['trivy-scan', 'sonarqube-scan']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/sonar-token/versions/latest
      env: 'SONAR_TOKEN'

# Logging
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'europe-west4'
  _REPOSITORY: 'testapp'
  _IMAGE: 'frontend'
  _SERVICE_NAME: 'frontend-app'

timeout: '30m'
